### ISSUE TITLE
BiblioCraft-like Desk Lamps

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#10]
They're quite aesthetic for indoor spaces and desk tops.

**Comment by jrddunbr** [comment]
Apparently we have a model for this already?

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.
