### ISSUE TITLE
Cable Pace

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#100]
Make sure that cable pace is correctly reflected in all parts of the mod. Problems in tip strips according to @Baughn

@OmegaHaxors: You can also take this up

**Comment by OmegaHaxors** [comment]
I've tried my best to fix it. It's a fundamental problem with the structure of the mod.
The config isn't being updated to the engine in time to commit the default var before it gets applied.

**Comment by jrddunbr** [comment]
Baugn is working on it.

**Comment by Grissess** [comment]
Fixed in 6ffe05384f0f00b2f571bb44fd55ad335920dbbe, which was merged in #111 .
