### ISSUE TITLE
*MOTOR*

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#114]
https://www.youtube.com/watch?v=hDDOweXvlKc

3x3x3 multiblock. Shaft exits on middle block on one side. Other side blows tons of particle effects.

Can be used to start shaft networks, but has to be either pre-heated or have a chance to warm up before producing power.

Can overheat if used for too long.

Uses *a lot* of fuel while running, and requires high-grade fuels.

**Comment by jrddunbr** [comment]
https://youtu.be/lPIHJwL1IYI

**Comment by jrddunbr** [comment]
I'm leaving this open because the code is almost there.

**Comment by AMIDIBOSS** [comment]
In terms of Model/Texture work, I'm offering my help. I do believe i can help as I've already created some of the original mod's models.

**Comment by jrddunbr** [comment]
Finished.
