### ISSUE TITLE
Sync Error with Config Copy tool

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#115]
Error where cables don't visually reconnect when copied in with a copy config tool.

**Comment by jrddunbr** [comment]
@Grissess can we fix this today or tomorrow? I'd like to push the new LLv11a build.

**Comment by jrddunbr** [comment]
It also appears to happen with any items that are copied into the system. Perhaps part of the same bug.

**Comment by Grissess** [comment]
@jrddunbr can you specify the exact blocks this occurs with? I had to call `reconnect()` in certain cases; I might have missed some of them.
