### ISSUE TITLE
"Save usage" typo in cables

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#12]

**Comment by jrddunbr** [comment]
I'll be going through the EN_Us and EN_CA and EN_BR or whatever they're called and fixing English translation woes across the board.

**Comment by jrddunbr** [comment]
Wow, I hadn't realized how horrible our translation coverage is. Even en_CA is pretty horrible. en_GB is like 4 lines!

**Comment by jrddunbr** [comment]
./src/main/java/mods/eln/sixnode/electricalgatesource/ElectricalGateSourceDescriptor.java

That file doesn't use ANY of the variables properly from my testing... What is going on here!?

**Comment by Grissess** [comment]
The typo's in the source; I fixed it, stashed the changes, and haven't pulled them back out again. I don't know if it's translated, but it's in addDescription or somesuch for ElectricalCableDescriptor, IIRC.
