### ISSUE TITLE
Mah TPS

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#124]
This function ***must*** to be cached.

https://github.com/jrddunbr/ElectricalAge/blob/4ec331de90938a7fd9660e71f69a28aa1305a5cc/src/main/java/mods/eln/mechanical/ShaftNetwork.kt#L67

**Comment by jrddunbr** [comment]
![ow](https://user-images.githubusercontent.com/14130505/52984568-09a32380-33be-11e9-9fda-303c742414e1.png)

**Comment by Grissess** [comment]
Eeyup. Easy fix, will get to it soon.
