### ISSUE TITLE
Lamp Supply Not Working

### ISSUE THREAD

**Issue by G1itch710** [jrddunbr/ElectricalAge#129]
Hey all, just wondering if anyone has had issues with the lamp supply in this version, i cant seem to get mine to work at all, all the channel names are set correctly and i have 50v set through the creative power supply, and the lamp it self says its connected to the lamp supply but the lamps dont turn on, they work if i directly connect them to cable

edit: im using ElectricalAge-jrddunbr-1.15.3

heres a screenshot

![Image](https://i.imgur.com/kHMGe0a.jpg)

**Comment by jrddunbr** [comment]
You've put cables in the lamp sockets, bulbs in the lamp sockets, there's power to the panel, right? ok.

Is this a special world ID by chance? Do other lights work? Do they work if you connect it directly to power and change the mode of the light to "powered by cable"? Just want to see if it's voltage problems, or a rendering problem.

**Comment by G1itch710** [comment]
i just tried it in a fresh new creative world and it still is not working, ive tried diffrent lamp sockets, bulbs cables nothing works, it also says its drawing 0 watts so yea, but if i connect the lights via direct cable they work fine, what i will try next is put electrical age in its own eviroment without any other mod except forge and test that, just to make sure no other mods are messing with it

**Comment by G1itch710** [comment]
i found the issue, i feel silly lol, so i had the channel name in the wrong spot, i kept naming the wireless channel not the power channel which is what it needed to be, so ive fixed it the issue lol.

can i make a suggestion though jrddunbr could we have a redesigned lamp supply GUI at some point its a little confusing for new people to the mod

this can now be closed :)

**Comment by jrddunbr** [comment]
Yeah, will do someday :) It's poorly labeled as it is, I agree.
