### ISSUE TITLE
DC-DC Issue and Relay Issues

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#137]
The DC-DC Converter Explodes with voltage type of cable even in correct configuration but if i use the current type of cable it does not explode.
Another issue is the use of relay (voltage type) similar but if i use current type of relay it does not explode. i used voltage type input output and relay (voltage type) explodes with same methodology applied on the DC-DC Converter test. If i used current type of relay with voltage cable it does not explode even with current cable
Version on: LLv12-Dev (1.16.0)

**Comment by jrddunbr** [comment]
Try the 1.16.1 release from yesterday. There was a small bug that affected the effective current limits on DC/DC converters that I fixed.

The relay type and the cable type you use must be the same generally (although current relays will work well with voltage cables). The reason for this is that the voltage cables have much higher resistance than the current cables, and when you use a voltage relay with a current cable, they will heat up artificially fast because it effectively acts like a resistor which rapidly increases the temperature of the relay. The switches will do the same, soon enough I'll be replacing the voltage system completely and the current cables will be all you need.

**Comment by setsunafseiei** [comment]
I was using the config file from my stable eln haha thanks

**Comment by setsunafseiei** [comment]
I did set it to 1000 or even 10000 and still it explodes
trying cableRsFactor to 1000.
my cablefactor to 5.0

**Comment by setsunafseiei** [comment]
>

> Try the 1.16.1 release from yesterday. There was a small bug that affected the effective current limits on DC/DC converters that I fixed.
> 
> The relay type and the cable type you use must be the same generally (although current relays will work well with voltage cables). The reason for this is that the voltage cables have much higher resistance than the current cables, and when you use a voltage relay with a current cable, they will heat up artificially fast because it effectively acts like a resistor, which rapidly increases the temperature of the relay.
> 
> The manual throw switches will do the same; soon enough I'll be replacing the voltage system completely, and the current cables will be all you need.
> 
> Also, check your Eln config file and be sure that `cableResistanceMultiplier` is set to `1000` or above, `1` is extremely unstable.

Still nothing sir, with updated and changed the value 1000 and 10000
also cableRsFactor to 1000
maybe i will try to adjust the cablefactor to 1 again

**Comment by jrddunbr** [comment]
CableRSFactor is not the one, just cableResistanceMultiplier.

**Comment by setsunafseiei** [comment]
> CableRSFactor is not the one, just cableResistanceMultiplier.

First i tried only cableResistanceMultiplier to 1000 then to 10000 and still nothing

**Comment by jrddunbr** [comment]
Alright, exactly which cables does this affect, can you give me an example circuit? (screenshot)

**Comment by setsunafseiei** [comment]
> Alright, exactly which cables does this affect, can you give me an example circuit? (screenshot)

any voltage cable from low to very high
![Screenshot (42)](https://user-images.githubusercontent.com/18274831/59193169-6a49ac80-8bb7-11e9-90c2-6510262b6a65.png)
![Screenshot (43)](https://user-images.githubusercontent.com/18274831/59193170-6a49ac80-8bb7-11e9-94f8-7b8c7163d425.png)
![Screenshot (44)](https://user-images.githubusercontent.com/18274831/59193171-6a49ac80-8bb7-11e9-9ab2-54e0c14187e7.png)
![Screenshot (45)](https://user-images.githubusercontent.com/18274831/59193173-6ae24300-8bb7-11e9-8fab-b3910382ab92.png)
![Screenshot (46)](https://user-images.githubusercontent.com/18274831/59193175-6ae24300-8bb7-11e9-8c87-b26de0528308.png)

**Comment by setsunafseiei** [comment]
Here is for the relay same with any voltage cable:
![Screenshot (47)](https://user-images.githubusercontent.com/18274831/59193247-a2e98600-8bb7-11e9-8ccc-9bec33749098.png)
![Screenshot (48)](https://user-images.githubusercontent.com/18274831/59193248-a3821c80-8bb7-11e9-97e6-7364248bf70d.png)
![Screenshot (49)](https://user-images.githubusercontent.com/18274831/59193249-a3821c80-8bb7-11e9-9d02-ef236623e4b2.png)

**Comment by setsunafseiei** [comment]
Also founded another problem but with probes:
![Screenshot (50)](https://user-images.githubusercontent.com/18274831/59193313-dcba8c80-8bb7-11e9-90df-9be1d1621cfb.png)
![Screenshot (51)](https://user-images.githubusercontent.com/18274831/59193315-dd532300-8bb7-11e9-85d0-11a84de1e2ba.png)
![Screenshot (52)](https://user-images.githubusercontent.com/18274831/59193316-dd532300-8bb7-11e9-9a66-b5a64cde4225.png)

**Comment by setsunafseiei** [comment]
Here with using current type of cable inside a probe test:
![Screenshot (53)](https://user-images.githubusercontent.com/18274831/59193379-1c817400-8bb8-11e9-9b87-8ba139ea5581.png)
![Screenshot (54)](https://user-images.githubusercontent.com/18274831/59193380-1c817400-8bb8-11e9-8dd6-0e60ae4bd577.png)
![Screenshot (55)](https://user-images.githubusercontent.com/18274831/59193381-1c817400-8bb8-11e9-8a2b-738b641c10ee.png)
![Screenshot (56)](https://user-images.githubusercontent.com/18274831/59193382-1d1a0a80-8bb8-11e9-8610-5ded66716afd.png)
![Screenshot (57)](https://user-images.githubusercontent.com/18274831/59193383-1d1a0a80-8bb8-11e9-9a41-d897d8360b3e.png)
![Screenshot (58)](https://user-images.githubusercontent.com/18274831/59193384-1d1a0a80-8bb8-11e9-8431-c58bbddc1c4e.png)

**Comment by jrddunbr** [comment]
Hmm. That looks like a return of the micro-resistance bug. Can you get it to happen with Current Cables at all, or is it only with the Voltage based cables?

**Comment by jrddunbr** [comment]
(also, I don't *think* that ground pin is going to do anything - the circuit from the voltage source to the ground pin is actually separate from the circuit to the probe, oddly enough apparently that can explode the probe.

**Comment by setsunafseiei** [comment]
> (also, I don't _think_ that ground pin is going to do anything) the circuit from the voltage source to the ground pin is actually separate from the circuit to the probe. That means that, oddly enough, apparently the micro-resistance can explode the probe as though it was a load.

even if the ground is not there it would still explode



> Hmm. That looks like a return of the micro-resistance bug. Can you get it to happen with Current Cables at all, or is it only with the Voltage based cables?

it works with any current cables without exploding and it only happens with any voltage based cables

**Comment by jrddunbr** [comment]
Replicated with Relay and Probes. Probably happens with hubs too.

**Comment by setsunafseiei** [comment]
> Replicated with Relay and Probes. Probably happens with hubs too. Edit: Yep.
> 
> I think it's a problem with VoltageWatchdog.

Yup it does and hubs act weird also

**Comment by jrddunbr** [comment]
Fixed in #139

**Comment by jrddunbr** [comment]
I think this fixes it all. Let me know if you encounter any more problems.

![2019-06-10_09 50 17](https://user-images.githubusercontent.com/14130505/59200028-55442d80-8b65-11e9-8411-ecd992530012.png)

**Comment by setsunafseiei** [comment]
> I think this fixes it all. Let me know if you encounter any more problems.
> 
> ![2019-06-10_09 50 17](https://user-images.githubusercontent.com/14130505/59200028-55442d80-8b65-11e9-8411-ecd992530012.png)

yup that is the temporary solution to my problem

**Comment by jrddunbr** [comment]
(see https://github.com/jrddunbr/ElectricalAge/releases/tag/1.16.1.1)

**Comment by setsunafseiei** [comment]
> (see https://github.com/jrddunbr/ElectricalAge/releases/tag/1.16.1.1)

thank you for your hardwork sir
