### ISSUE TITLE
Autominer not using full capacity of a double chest

### ISSUE THREAD

**Issue by Caeleron** [jrddunbr/ElectricalAge#141]
When an autominer places items into a chest, it will treat the chest inventory as a single chest and use the half that corresponds to the block it is interacting with it. Basically, it treats a double chest as a single chest.

**Comment by jrddunbr** [comment]
Hmmm

```java
private IInventory getDropInventory() {
        IInventory chestEntity = null;
        for (int x = 2; x >= 1; x--) {
            Coordonate c = new Coordonate(x, -1, 0, miner.world());
            c.applyTransformation(miner.front, miner.coordonate());
            if (c.getTileEntity() instanceof IInventory) {
                chestEntity = (IInventory) c.getTileEntity();
            }
        }
        return chestEntity;
    }
```

This feels like cancer. I have some problems with this code; it picks the *last* chest it finds, applies some strange transformation, and then eventually gets back an class with instance of `IInventory` to return (or null if not). The fact that that doesn't return a *whole* chest makes me question Minecraft's ability to reference chests as a single unit.

**Comment by Caeleron** [comment]
Would this work perhaps?
`
    private TileEntityChest getDropInventory() {
        TileEntityChest chestEntity = null;
		Coordonate outputLocation = new Coordonate(1, -1, 0, miner.world());	
		outputLocation.applyTransformation(miner.front, miner.coordonate());
		if (outputLocation.getTileEntity() instanceof TileEntityChest) {
			chestEntity = (TileEntityChest) outputLocation.getTileEntity();	
		}
        return chestEntity;
    }
}
`

**Comment by jrddunbr** [comment]
I'd have to look. The method signature is not a drop-in replacement.

**Comment by jrddunbr** [comment]
So that technically worked, but it didn't fill the other half of a double-sided chest :(

**Comment by Caeleron** [comment]
Bummer. I made the assumption that MC would handle the double chest on its own, but apparently not. Having each implementation of something that interacts with an entity handle double chests seems like a bad idea, but Mojang didn't think that would be an issue. Should the code be modified to handle the two chest blocks separately, that could cause weird effects. It wouldn't matter if the chest blocks are in any way connected; it would be treated as a double chest if they are next to each other. Even if it did check to see if the blocks were the same id, some mods' chests don't form double chests, but they would be treated as one anyways. I want to see how vanilla hoppers and other mods are resolving this.

**Comment by Caeleron** [comment]
After looking at how vanilla hoppers handle it, it turns out all Blocks that are classified as BlockChest have this special function that gets the double chest inventory if it is part of a double chest. Here's what I have now:
```
    private IInventory getDropInventory() {
        IInventory inventoryEntity = null;
		Coordonate outputLocation = new Coordonate(1, -1, 0, miner.world());	
		outputLocation.applyTransformation(miner.front, miner.coordonate());
		if (outputLocation.getTileEntity() instanceof IInventory) {
			inventoryEntity = (IInventory) outputLocation.getTileEntity();	
			Block inventoryBlock = miner.world().getBlock(outputLocation.x, outputLocation.y, outputLocation.z);
			if(inventoryBlock instanceof BlockChest) {
				IInventory possibleDoubleInventoryEntity = ((BlockChest)inventoryBlock).func_149951_m(miner.world(),outputLocation.x, outputLocation.y, outputLocation.z);
				if (possibleDoubleInventoryEntity != null) {
					inventoryEntity = possibleDoubleInventoryEntity;
				}
			}
		}
        return inventoryEntity;
    }
```
This is pretty much how vanilla hoppers handle it, but there might be a better way to handle this than to do the double chest check every time the miner wants to put an item into a chest.

**Comment by jrddunbr** [comment]
Hmm. I'll look at that then...
