### ISSUE TITLE
"Wall mountable" DC-dc converter, Batteries and Thermal Dissipators

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#145]
I would like to request these blocks to be wall mountable

**Comment by jrddunbr** [comment]
That's probably not going to happen. Make a shelf.

**Comment by setsunafseiei** [comment]
I have a design already for battery shelf which connects capacity oriented batteries in 16S/5P Configuration and the space is the reason why i created capacitor bank

**Comment by jrddunbr** [comment]
Can't you use any regular Minecraft block? Why should I be implementing a shelf?
