### ISSUE TITLE
Large Capacitor, Large Inductors (similar to rheostat to large rheostat)

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#146]
I would like to request Large Capacitors which holds more energy, have more farads and nominal voltages also with Large Inductors which is similar to the rheostat to large rheostat upgrade but without adjustability and cooling support

**Comment by jrddunbr** [comment]
Is there a particular situation where either component is lacking capacity? I've had no problems with the amount of inductance/capacitance provided at maximum.

**Comment by setsunafseiei** [comment]
Well it really depends on the application especially when i make capacitor power bank or buck or boost converters, super capacitors is like large capacitors, in inductors it is already decent enough for me

**Comment by jrddunbr** [comment]
If you want something akin to a super capacitor, might I suggest using the high current batteries? They are really good for this kind of thing. High capacity capacitors probably don't make a lot of sense unless you're fully discharging them - and I have not really seen many designs in Eln that would benefit from it, versus just having 2 or 3 capacitors in parallel to meet your needs.

**Comment by jrddunbr** [comment]
If you ever want a larger capacitor, just let me know, it's just not very high on my priorities list right now, and I think the existing one is pretty OK.

**Comment by setsunafseiei** [comment]
i just prefer more voltage though and it is okay if it is cancelled anywawy i would like it better if the "pcb" like concept would be better
