### ISSUE TITLE
New probes

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#152]
I would like to request new probes particularly for batteries with charge percentage probe and especially temperature probe also for generators or shaft motor for temperature checking

**Comment by jrddunbr** [comment]
We have all of these already. Thermal probes measure temperature, voltage probe + sigproc function is percent readout of batteries.

**Comment by setsunafseiei** [comment]
How to do sigporc?

**Comment by jrddunbr** [comment]
https://wiki.electrical-age.net/index.php?title=Signal_Processor
