### ISSUE TITLE
Brushless DC Shaft Motor and Electronic Speed Controller

### ISSUE THREAD

**Issue by setsunafseiei** [jrddunbr/ElectricalAge#154]
I would like to request a Brushless DC Shaft Motor in which it is similar to the Shaft Motor on the mod but with signal input which can be used to control the speed of the Shaft Motor wherein the electronic speed controller itself is built into the Shaft Motor

**Comment by jrddunbr** [comment]
This can be done with the circuits in the mod relatively easily, but the variable inductors update will definitely help.

**Comment by setsunafseiei** [comment]
By using rheostats and large rheostats right?

**Comment by jrddunbr** [comment]
That's one way to do it, but inductors don't heat up as much and do a relatively good job limiting rush currents.
