### ISSUE TITLE
I cannot cover blocks at all

### ISSUE THREAD

**Issue by zalein1** [jrddunbr/ElectricalAge#155]
For whatever reason I am not able to hold C and cover a wire like I used to. I made sure in my controls that C was my default wrench key. I am using jrddunbr's latest version on his fork.

**Comment by jrddunbr** [comment]
This is a known bug that will be fixed relatively soon.

**Comment by jrddunbr** [comment]
Right. Fixed in f4b1ac8f1f8cdee96c370fd6d558f7df238b0a0d
