### ISSUE TITLE
New Disconnect Models?

### ISSUE THREAD

**Issue by zalein1** [jrddunbr/ElectricalAge#156]
![image](https://user-images.githubusercontent.com/52048359/59984697-1a74d780-95f2-11e9-9382-731613245119.png)

**Comment by jrddunbr** [comment]
If you can model it...

**Comment by zalein1** [comment]
Okay for sure. I will look in to it

**Comment by jrddunbr** [comment]
We use blender: https://www.blender.org/

If you send be a .blend file with a UV map, I'll look into it when next update comes around.

**Comment by Grissess** [comment]
Correction: we use .OBJ and .MTL files in the mod's loader.

Blender is a free (gratis/libre) software multimedia suite that includes good modeling support, but the mod itself doesn't _depend_ on it :) . Nonetheless, all the model assets I know of were therein made. I'm still not going to judge if someone is more comfortable with another modeling tool that can make .OBJ/.MTLs.

**Comment by jrddunbr** [comment]
In general since almost everything here has been done in Blender, I don't want to exactly change that trend. Like @Grissess said though, I'll accept the OBJ/MTL format directly.

**Comment by jrddunbr** [comment]
I'm going to close this since there's nothing going on, but if you have a model, I'll reopen it. I think the current devices we have are sufficiently interesting - we already have a knife switch that has almost the same style of movement.
