### ISSUE TITLE
Shaft modifications cause their null checks to cause zero-velocity corrupted shafts

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#158]
To replicate -

Create a shaft network with multiple clutches contained. Start the shaft with your favorite motive power. Explode part of the shaft (a generator overheat will do the trick). Watch as the weights go to 0, NaN's traverse the network,... It's great!

**Comment by jrddunbr** [comment]
Fixed in #157

**Comment by Grissess** [comment]
Any progress on this bug in mainline as far as we know?

**Comment by jrddunbr** [comment]
It doesn't NaN anymore but it forgets the mass and energy

**Comment by jrddunbr** [comment]
You may have seen the result of this as the "spooky action at a distance" bug.

**Comment by jrddunbr** [comment]
If I ever want to see this done, I'll probably have to do it myself...
