### ISSUE TITLE
ELN steam production.

### ISSUE THREAD

**Issue by GrimmDemon** [jrddunbr/ElectricalAge#165]
Steam for steam turbines has to come from somewhere, and that means a different mod. Now that's not a problem, since Rail Craft is perfectly compatible and Build Craft pipes do an adequate job of moving water, fuel and steam around, but the Rail Craft way of generating steam is tedious at most. The steam boilers do reach 1 000 degrees °C, but they take a very long time to reach that, especially the large 3x4x3 configuration, which is still inadequate to power a couple steam turbines during "spin up". I was thinking, if I could use the heat furnaces, either solid or fuel heat, to boil water to create steam, it'd be so much easier, and faster.
![2019-07-16_12 43 12](https://user-images.githubusercontent.com/52752989/61289613-ff008500-a7c9-11e9-9083-4e625003fc7c.png)
A 1x1x1 configuration with a fuel heat furnace as a source of heat instead of the standard fire box.
![2019-07-16_12 43 41](https://user-images.githubusercontent.com/52752989/61289672-26efe880-a7ca-11e9-971f-ecdcc2b072ef.png)
2x2x2 configuration
![2019-07-16_12 44 21](https://user-images.githubusercontent.com/52752989/61289677-3111e700-a7ca-11e9-8a7d-cb1ceb895151.png)
3x3x3 configuration
The 25kW burners for the fuel heat furnace would be best suited for a job like this, they are a little OP when used for standard power generation using heat turbines.
This has been a nagging issue for me, because, usually, when I build power stations, I go big, and I tend to use as much of the generated power as possible, I even turn to using admin steam producers whilst my boilers are busy heating up.

**Comment by jrddunbr** [comment]
Something like this is planned, but the port needs to be completed first.

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.

**Comment by jrddunbr** [comment]
This functionality was added with the new thermal heat exchanger.
