### ISSUE TITLE
Variable ratio DC/DC converter

### ISSUE THREAD

**Issue by mario2582** [jrddunbr/ElectricalAge#174]
Add Variac's

Add variable transformers also called variac's

**Comment by jrddunbr** [comment]
This may be feasible in the long term, but right now it is not.

**Comment by setsunafseiei** [comment]
When will this release?

**Comment by setsunafseiei** [comment]
is it possible to be done by the 1.17.x update?

**Comment by jrddunbr** [comment]
The closest I'm getting to this is the Variable DC/DC converter which will be added with PR #190
