### ISSUE TITLE
Add a actual dimmer switch (No Rheostat comments please) [long term]

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [jrddunbr/ElectricalAge#178]
Add a actual dimmer switch to electrical age 

### **No "you can make this with a Rheostat comments please"**

Trying to make a dimmer with a rheostat in electrical age is very finicky, you have to select the right amount of coal dust and get the resistance just right for your load to make dimming work properly and as soon as you add more lights to your circuit or if your using all led and you change the bulb type to something else that uses more power on one fixture it messes up the whole thing so it doesn't dim properly.

a proper dimmer should be able to dim lights smoothly on a circuit with any kind incandescent bulbs as long as they didn't exceed the dimmers wattage rating, for led it would only work with so many LED's (eg 150w of LED) like in real life before it would be over loaded and issues happened,

their should be 3 types of dimmers

Standard dimmer - works with incandescent lights (600 - 1000w max)
LED dimmer - works with leds (150 - 250w max)
Fan Dimmer - has a few preset speeds and designed to not burn out motors like real fan dimmers do in real life (4 amp max)

**Comment by jrddunbr** [comment]
This is really stuff that would be done with the variable DC/DC converter idea (since variacs are not possible)
