### ISSUE TITLE
Add Various Pole and Various Throw Switches

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [jrddunbr/ElectricalAge#179]
Add Various Pole and Various Throw Switches

You currently have Single pole single throw switches implemented.

- [ ] Single Pole Double Throw switch

A single pole double throw switch connects an input terminal to one of two output terminals. Thus, a double-pole switch has three terminals. One of the terminals is called the common terminal. The other two terminals are often referred to as A and B.

You would usually need a single pole double throw switch to deliver power to one of each of the two wires in a motor that determine the spin direction of a motor.

- [ ] Double Pole, Single Throw switch

A DPST switch turns two circuits on or off. A DPST switch has four terminals: two inputs and two outputs.

- [ ] Double Pole Double Throw switch

A DPDT switch routes two separate circuits, connecting each of two inputs to one of two
outputs. A DPDT switch has six terminals: two for the inputs, two for the A outputs, and two for the B outputs.

- [ ] Triple pole switches and all their configurations

3P3T, DP3T, SP3T, 3PST, 3PDT

**Comment by jrddunbr** [comment]
I see no purpose in this. More importantly, you can't really fit these in a single block.

I can see a 3 way switch that flips over a central wire, but that's it.
