### ISSUE TITLE
Make it so we can "Pop a Electric meter" the photonicinduction way

### ISSUE THREAD

**Issue by mario2582** [jrddunbr/ElectricalAge#184]
Make it so we can "Pop a Electric meter" the photonicinduction way in a future version of EA

by photonicinduction way, make a step down transformer in a home and connect it to a low voltage home supply and make it so it steps down the voltage to like 0.5 volts, but the amperage goes up around 10,000 - 20000 amps

then all you need to do is run current through the transformer+ through a electric meter and back to the transformer- until it pops

Also make it so that when your drawing too much power through the meter and you built houses with electricity for neighbors it causes the voltage to drop on the mains causing the neighbors lights to flash too... another example is if someone's stick welding at a high working current, your lights may flicker.

Quote of the day
"Hey Mom, the neighbor is torturing his electrical system again, Gerald get away from the window"

[Popping the meter](https://www.youtube.com/watch?v=ut5DXxK1dvk)

**Comment by jrddunbr** [comment]
I'm not sure I understand what you're saying, but the things he does in that video are roughly possible minus the amperage limits of the cables in the mod.
