### ISSUE TITLE
ETA for Electrical Age 1.12.2?

### ISSUE THREAD

**Issue by GrimmDemon** [jrddunbr/ElectricalAge#185]
Currently this the only active fork for Electrical Age I've come across.
I'm currently stuck using 1.12.2 because the idiot I am deleted my forge for 1.7.10, and pretty much everything else 1.7.10 related. I've been using 1.12.2 for a while now and, as a tinkerer at heart, I'm really starting to miss using Electrical Age.
is there any projects going on for 1.12.2, or at least, any hope for 1.12.2? I might go back to 1.7.10, but that'll be after I re-download the 87 mods that I had for that version.

**Comment by jrddunbr** [comment]
It's going to be a long time before it's ready. I estimate summer of next year at the earliest. There's a ton of stuff to do and basically nobody besides me to do it.

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.
