### ISSUE TITLE
Solar Panel Efficiency 

### ISSUE THREAD

**Issue by mario2582** [jrddunbr/ElectricalAge#187]
Has Solar panel efficiency been simulated yet... the efficiency should be displayed in the info box in the crafting menu on panels,

the bigger ones should have a higher efficiency than the smaller ones

but they should not go over 25% efficiency since no panel exists in real life that is above that except ones that the government and big power may be suppressing.

https://www.solar.com/learn/solar-panel-efficiency/

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.
