### ISSUE TITLE
Volatility of the variable DC/DC converter

### ISSUE THREAD

**Issue by GrimmDemon** [jrddunbr/ElectricalAge#191]
I found another instance of my minecraft on my hard drive, that I probably forgot to delete when I moved to an SSD.
I downloaded and played around with the testing build of the variable DC/DC converter and I noticed a big tendency to blow stuff up quite easily using a regulatory system, in my case, basically a electrical probe that tells the converter what voltage to put out.
I decided to use a power capacitor (50V/100mF) and it seemed to solve my issue, or kinda just circumvented imminent disaster as it now no longer responded to sudden voltage as good as it did without a cap, but I did get less explosions, 50% because of the experience I earned from setting up my buck/boost systems, and 50% because of the smoothing properties of the cap.
That made me wonder why there isn't any signal capacitor. It would be a great help to smooth out the responsiveness of such regulation systems, plus it will mitigate the effects of lightning disturbance on certain wireless systems.
The signal capacitor doesn't need to be complex like the power capacitor, plus the model for the power capacitor can be used for the signal capacitor.
If we have a signal relay and a signal doide, doesn't it make sense to add a signal capacitor?

**Comment by jrddunbr** [comment]
You're almost surely looking for the Low Pass Filter device. It acts similarly to a capacitor

**Comment by GrimmDemon** [comment]
Cutoff frequency of 0.020 Hz works perfectly. Never realized that the LPF could do that. Frankly, I haven't really the foggiest idea of what most of those chips do, specifically the PAL device.

**Comment by jrddunbr** [comment]
No problem! They are sometimes useful chips.

I haven't found many uses for the PAL but it's probably a good component to build logic gates from.
