### ISSUE TITLE
Variable DC/DC Converter Bug

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#194]
To replicate:

Place two Variable DC/DC converters next to one another (signal side) and don't connect any signal cables. Game will crash.

**Comment by GrimmDemon** [comment]
This also corrupts the world and prevents it from being reloaded, making the world unplayable

**Comment by jrddunbr** [comment]
We think we have determined why this happened - it's likely due to a NaN (ugh!) in the signal cable input when there are two inputs but no output voltage.
