### ISSUE TITLE
Make a non "swinging" version of the suspended lampa ? 

### ISSUE THREAD

**Issue by smmarkvard** [jrddunbr/ElectricalAge#198]
Would it be possible to make a non "swinging" version of the suspended lamps?

great innitiative by the way, for taking up this wonderful mod and make it even better :-)

**Comment by jrddunbr** [comment]
Yes, it would be possible. The question comes down to whether I want to make a new fixture or if I just make it so that it can be changed in the UI.

**Comment by jrddunbr** [comment]
New fixture it is. I can't imagine placing a few billion of them and then clicking each one to set them not to swing...

**Comment by jrddunbr** [comment]
This will be released with 1.15.12
