### ISSUE TITLE
Add Rodents

### ISSUE THREAD

**Issue by mario2582** [jrddunbr/ElectricalAge#199]
I thought that this should be added when I saw the photo...

![squirrel](https://user-images.githubusercontent.com/11165643/69485753-f6702900-0e11-11ea-8c62-55972da0aff7.jpg)

They may look cute and cuddly, but this pest is the ultimate wiring destroying machine.

Add rodents as mobs like squirrels, rats, and mice etc and add the ability for them to have to potential to chew wiring that would be poorly placed such as on the ground or laying flat on the floor and not covered like in attics etc and not protected in area's rodents could spawn.

![chew](https://user-images.githubusercontent.com/11165643/69485784-4222d280-0e12-11ea-929e-129b2a9f6d3f.jpg)

Also, add some form of rodent trap such the classic victor snap trap that could be placed to catch rodents that spawn in area's you would want wiring protected. 

![rat-wires](https://user-images.githubusercontent.com/11165643/69485811-b9f0fd00-0e12-11ea-9629-ddc846cdc526.jpg)

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.

**Comment by jrddunbr** [comment]
I don't think this will ever be implemented.
