### ISSUE TITLE
Is Electrical Age Open Source?

### ISSUE THREAD

**Issue by mario2582** [jrddunbr/ElectricalAge#205]
@jrddunbr - Is Electrical Age Open Source?

If it's open source I was thinking of creating my own version of EA and porting parts of it into MCreator to speed up development.

**Comment by Grissess** [comment]
For posterity, to whomever else looks this up:

Electrical Age's is licensed under the Lesser GNU General Public License, version 3.0, and assets are released under the Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License. For more information, please see`LICENSE.md` in the repository root.

**Comment by jrddunbr** [comment]
Just for reference, MC Creator is a very basic program, and it will not be able to handle the complexity of Electrical Age. For the number of times I've heard that, I could buy a pizza.

People who suggest that (no offense) have little to no coding experience and have no idea what goes into a complex program like Eln.
