### ISSUE TITLE
Multimeter not displaying correct values on analog microchips

### ISSUE THREAD

**Issue by dennis-qt** [jrddunbr/ElectricalAge#209]
When probing analog microchips with the multimeter, values are treated as digital values. So input signals below 10V are shown as "0", signals from 10V to 30V are shown as "?" and signals above 30V are shown as "1". Outputs are always shown as "0" except when the output signal is _clamped down_ to 50V (for example a summing unit with two inputs that, when summed, result in a number greater than 100%)

**Comment by Grissess** [comment]
Tracked down to [this implementation](https://github.com/jrddunbr/ElectricalAge/blob/a11f6ebc4b6433164d0d422093ce441be1f323a3/src/main/java/mods/eln/sixnode/AnalogChips.kt#L143-L154).

What would we rather it display instead? "Signal voltages"? Floating point values?

**Comment by dennis-qt** [comment]
I'd say floating point values since the values are 0 - 1 for the digital chips

**Comment by jrddunbr** [comment]
@Grissess The chips show signal voltages in waila so I would stay consistent with that.
