### ISSUE TITLE
No lights seem to work after the last update.

### ISSUE THREAD

**Issue by ransom3910** [jrddunbr/ElectricalAge#216]
First off thank you very much for the continued work on this mod. The new updates are great!

 In this last update none of the lamps will light up when powered by cable.  I am able to get them to light up if I use a lamp supply.   Also the lights appear to be on but they are not radiating any light to their surroundings.

**Comment by jrddunbr** [comment]
Use the latest stable, 1.15.11, because 1.16.5 has a handful of bugs. This is a known issue for some time now.

**Comment by jrddunbr** [comment]
Fixed in 1.16.6
