### ISSUE TITLE
Rain falls through covered SixNode blocks

### ISSUE THREAD

**Issue by Mr-burnt-mayonnaise** [jrddunbr/ElectricalAge#225]
i cant say more, it just happens (sorry for my bad english)
![2020-09-28_19 32 58](https://user-images.githubusercontent.com/53156297/94492902-b6ac6780-01c1-11eb-8793-b7ccf646f1e7.png)

**Comment by jrddunbr** [comment]
It does happen. I'll fix it one of these days.

**Comment by Grissess** [comment]
Bad news: in 1.7.10, the Block class' `isOpaqueCube` is nilary, so it can't be specialized for specific blocks in the world. A viable workaround might be to have two different Block class instances (one which is, and one which isn't) and switch between the two at runtime--fortunately, our simulation doesn't depend on blocks much.

Good news: as of 1.12.2, that method is unary (taking an `IBlockState`), so this can be solved in the 1.12.2 port with a separate block state--which is moderately akin to the "multiple class instances" above.

**Comment by jrddunbr** [comment]
I doubt this will be worth the effort.
