### ISSUE TITLE
[Feature request] Please add the ability to cover cables with all minecraft blocks (or at least wood/logs)

### ISSUE THREAD

**Issue by cryokesh34** [jrddunbr/ElectricalAge#239]
Hello, could you please add the ability to cover cables with every block in minecraft? Or at least with wood/logs (like oak wood).

(Also I didn't know how to post this as a feature request.)

**Comment by jrddunbr** [comment]
You can already do this by holding `C` and then right clicking the block on a cable.

**Comment by cryokesh34** [comment]
But not all blocks are supported (or at least it did not work form me). With wood/logs, it just said "Wire color care (number 1 or 0)" With planks, glass etc. it works, but with wood/logs it doesn't.

**Comment by jrddunbr** [comment]
Handled on Discord.
