### ISSUE TITLE
Fix Textures for T2 pole, Grid Transformer

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#24]
SeilaPlay has submitted me some updated icons for the T2 pole and grid transformer to fix the currently poorly rendered items in the inventory.

I'm not sure if we can use them, because they may be rendered in the inventory on the spot (in which case, @Grissess is going to look at it since he knows graphics better than I do).

**Comment by Grissess** [comment]
Putting an icon in the inventory is easy, it's just another texture filtered with GL_NEAREST.

@jrddunbr do you have said assets around? :)

**Comment by jrddunbr** [comment]
![griddc-dcconverter](https://user-images.githubusercontent.com/14130505/42907959-7ab02f24-8aad-11e8-9a7a-d45b32170283.png)
![transmissiontower](https://user-images.githubusercontent.com/14130505/42907960-7ac398c0-8aad-11e8-839d-791cb9e498de.png)

Licensing is like the rest of the images in the repository. I asked.

**Comment by Grissess** [comment]
![2018-07-18_20 51 51](https://user-images.githubusercontent.com/1500742/42915220-810177e2-8acc-11e8-84da-3b82e34d3891.png)

Look good to you?

**Comment by jrddunbr** [comment]
`SeiláPlay` sent me the texture.

Looks good.
