### ISSUE TITLE
creative cable enhancement suggestion

### ISSUE THREAD

**Issue by Electricianfromhell** [jrddunbr/ElectricalAge#247]
the creative cable is currently way too large which makes it very hard to work with relays, signal probes etc used with it.

i have a enhancement suggestion..

- [ ] make in the same size of the Ultra High Voltage Cable
- [ ] make the default color purple like in the image of the creative cable
- [ ] make it have the wording "Creative Cable / 51.2 Kv / 15 Ka / 768000 Kw" written on the textures the cable uses similar to how most wiring in real life has a description of what it is written on the wire every few feet.

**Comment by jrddunbr** [comment]
We're likely removing them next update because of bugs, so this won't be relevant.
