### ISSUE TITLE
write Voltage/Current/Wattage nominals on cables

### ISSUE THREAD

**Issue by Electricianfromhell** [jrddunbr/ElectricalAge#248]
since i suggested doing it with the creative cable...

all other cables should have their Voltage/Current/Wattage nominals written on them like in real life.

for example for the Very High Voltage Cable

"Very High Voltage Cable / 3.2 Kv / 4.69 a / 15 Kw"

**Comment by jrddunbr** [comment]
They have it in the tooltip since forever.

![2021-01-21_23 46 24](https://user-images.githubusercontent.com/14130505/105447854-103e1380-5c43-11eb-8dbf-f29c91b50699.png)
