### ISSUE TITLE
We can pass the nominal power of cables easily.

### ISSUE THREAD

**Issue by Welbre** [jrddunbr/ElectricalAge#252]
Hi, before yours read, sorry for my english. I'm from Brazil.

well, i found a way for pass the nominal power and current of cables (above the maximums power of cables), and the cables not explode and gets stable.

I use to exemple the 200v cable, they have a maximums current in the 12A, and i pass 38A easily.
I only can do it because the power resistor have a 10mOhm(when we not put coal dust inside), and he can dissipate more heat that the 200v cable.

Soon, when i put the resistor in a cable, the resistor working how a cooling to te cables, so avoiding the explosion.

[https://imgur.com/a/lumN1MW](https://imgur.com/a/lumN1MW)
[https://imgur.com/a/GARnuYR](https://imgur.com/a/GARnuYR)
The 200v cable passing 4,30Kw at 37c, and the corret cable to this power at 92c

[https://imgur.com/a/Fw6UjPo](https://imgur.com/a/Fw6UjPo)
The 200V 2Kw 10A cable passing 38A, in this test I left it for 10 minutes until it stabilized at 130c

thank for your time; I wish there were more cables for the same voltage.

**Comment by Welbre** [comment]
This is not a bug, but a way to crack the cables of the mod, so I created this post to be able to report

**Comment by jrddunbr** [comment]
Hey, thanks for the bug report! I think I know why this is broken (it is in fact a bug with our `Line` optimizer implementation), and will probably have a fix out in the nearby future for it.

**Comment by jrddunbr** [comment]
> I wish there were more cables for the same voltage.

What do you mean by this; different current tiers?

**Comment by Welbre** [comment]
> > I wish there were more cables for the same voltage.
> 
> What do you mean by this; different current tiers? As it stands, you can color the cables for aesthetic reasons (but it also causes cables to not connect, unless you change color care), it doesn't affect any of the cable's properties.

I saying about have more subdivision in a same voltage tier.

example:
High voltage cable T1:
  Nominal Ratings:
    Voltage: 800v
    Current:3,125‬A
    Power: 2,5Kw
    resistance: 100mΩ

High voltage cable T2:
  Nominal Ratings:
    Voltage: 800v
    Current:6,25A
    Power: 5Kw
    resistance: 200mΩ

High voltage cable T3:
  Nominal Ratings:
    Voltage: 800v
    Current:8,75A
    Power: 7Kw
    resistance: 280mΩ

This is only an idea, to we not dependence completely from colored cable, i like the colored cables, but when i need create some  big power plant, i need place 8 or 10 colored cable lines connected on same pole, this use lots of space.

I'm not complaining this is just an idea :)

**Comment by jrddunbr** [comment]
I'm not certainly why you are increasing the resistance with the current limit of the cable.

**Comment by Welbre** [comment]
> I'm not certainly why you are increasing the resistance with the current limit of the cable.

To create a balance in between the tiers of a same voltage cable, so, you are need to think what is the best cable for used, for not have bigs lost of power or voltage.

example:

i'll connect a 2kw machine on my 800v power system, so the cable needed pass 2,5‬A, the T1,T2,and T3 will suport the current, but the T3 cable have a more resistance, so the T3 have more lost of power compared with the T1.

HV cable T1: Will lost  0,625‬W/cable when the cable has pass 2,5A
HV cable T2: Will lost 1,25‬W/cable    when the cable has pass 2,5A
HV cable T3: Will lost 1,75W/cable    when the cable has pass 2,5A
I use this expression to calculate the power lost: P=I²*R

If you go create tiers on a same voltage cable(how i show above), the different tiers will needed a balance, because the T3 cable
would be all time used, and the T2 and T1 cable it would practically be useless, because have a same resistance that T3,but pass less current.
This is my idea to balance the new cables(if implemented), but you simply can made a very hard recipe for the T3 cables, this will do the T1 and T2 more attractive(worth).
