### ISSUE TITLE
Electric Furnace explodes cables on world load due to current spike

### ISSUE THREAD

**Issue by Welbre** [jrddunbr/ElectricalAge#253]
Hi,the title says it all, i have this problem in my generators and now the problem is happen in the cables; I think this a bug, because i can't found any why for the explosions, and some time the generator and cables not explode when i open the world.

I have maked this video to show the problem, and put the map for download,

[https://youtu.be/QogrnjaccWo](https://youtu.be/QogrnjaccWo)

Thanks.
[BugReport eln.zip](https://github.com/jrddunbr/ElectricalAge/files/5936350/BugReport.eln.zip)

**Comment by jrddunbr** [comment]
Odd. I've very rarely seen this happen.

I think it is related to the electric furnaces you have set up there. I'd have to look closer at it later.

**Comment by Welbre** [comment]
> Odd. I've very rarely seen this happen.
> 
> I think it is related to the electric furnaces you have set up there. I'd have to look closer at it later.

Maybe,i think this on more bug with the dc converter, he is be very bugged, i have made some test with the stone furnace system, measuring the output 200v, temperature in the output and input from turbine, and measuring the voltage in the dc converter output.

My test:
[Photo1](https://imgur.com/a/FsgvqPy)
[Photo2](https://imgur.com/a/qvlWEVJ)
[Photo3](https://imgur.com/a/8rce0AC)
The Photo1 is the system when i turn on the furnace.
The Photo2 is a voltage drop when i load the world.
The Photo3 is my test stone furnace system.
I Have 3 probes the Green(0-15kw),Red(0-4kv),and Blue(0-240v)

You can see in the Photo3 the dc converter be directly connected at the turbine,i am having problems when i make a direct connection between a dc converter and a electric furnaces, but not getting anything exact to report.

**Comment by jrddunbr** [comment]
Ah, yeah, there's a current bug with the electric furnaces on world load. I'll have to look into it.

**Comment by Venomity268** [comment]
Hi, this is the same issue I was telling you about on discord, inductors still haven't fixed the issue... everything just blows. It doesn't happen with furnaces alone. Just as Welbre described with loading the world.

**Comment by Venomity268** [comment]
Also, it doesn't happen all time, it's almost like it happens when you are close proximity to the cables and generators when loading the world. I have been experiencing this from 1.16.10 upwards so I am stuck with 1.16.9 for now.

**Comment by Welbre** [comment]
> Hi, this is the same issue I was telling you about on discord, inductors still haven't fixed the issue... everything just blows. It doesn't happen with furnaces alone. Just as Welbre described with loading the world.

I see the current spike exploding the cables, and i see too the generators exploding because a little voltage drop create when i load my world. I'll do some test and post in a new issue. I thinking this is 2 different bugs.

**Comment by Welbre** [comment]
@jrddunbr,

I did the tests that I mentioned in the comment above, I made 8 different systems with the electric furnace, and the macerator, connector to a dc converter (which may or may not have a cable between them), and with or without a pole system feeding everything.
Here is the video, you can choose which of the 8 tests you want to see in the links in the video description.
[https://youtu.be/nLRX8KlwzHo](https://youtu.be/nLRX8KlwzHo)
Conclusion:
-When charging the world, electric furnaces create a current spike. (cause of my issues)
-The cable between the converter and the furnace (or macerator) creates a different behavior when energizing the system.(i had see happen in another furnace system, but the explosion happen when i turn on the system.)
-Voltage drop in the dc converter when we charge the world.(I had some problems when the dc converter feed the poles.)

**Comment by Venomity268** [comment]
This is exactly the bug that I am experiencing. Because I have a power farm with 3 villages, I  am experiencing mass explosions too making the new versions unplayable.
