### ISSUE TITLE
[Suggestion] CraftTweaker Support

### ISSUE THREAD

**Issue by JadianRadiator** [jrddunbr/ElectricalAge#262]
I would like to request that you add CraftTweaker support so that people (me) can customize or otherwise add recipes to/for stuff in Electrical Age crafting machines.
http://minetweaker3.powerofbytes.com/
http://minetweaker3.powerofbytes.com/downloads.html

**Comment by jrddunbr** [comment]
Electrical Age is not getting new features. Eln2 is what we are developing now.
