### ISSUE TITLE
Signal Diode Fix

### ISSUE THREAD

**Issue by jrddunbr** [jrddunbr/ElectricalAge#28]
![2018-07-18_23 22 49](https://user-images.githubusercontent.com/14130505/42919801-9fb5929e-8ae1-11e8-9277-8973a733ed04.png)

**Comment by Grissess** [comment]
Argh.

For now, diodes are equivalent in simulation to two probes comparing voltage hooked up to a relay. They're obviously a bit more compact, but you can use that for a workaround.

**Comment by jrddunbr** [comment]
Perhaps it would be possible to perform an optimization since current isn't used on signal cables.

**Comment by jrddunbr** [comment]
@Grissess looked into this. I came to the realization that the way Signal cables are currently implemented makes them very resistive- which means that increasing the resistance doesn't quite work to make these things act like switches. We need to look into lowering the resistance on these cables.

**Comment by jrddunbr** [comment]
On second thought, I think that we'll be removing the signal system anyways in an upcoming major change I want to do. Everything will use low-current cables.
