### ISSUE TITLE
Attempt to iteratively solve MNA

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#31]
This is very experimental and might never be production-ready.

Some components, like diodes, can only ever react to changes _ex-post facto_--they need to _observe_ a state change before they can do something about it, and by the time they do something about it, the state which invoked that change may have already passed. This is especially noticeable in the typical inductor-kickback circuit, where the -V instigated by an inductor lasts for only one tick, too short for a reverse-bias diode to correctly forward-conduct it--however, it does correctly conduct the normal positive V because it catches the inductor's charging current, which is not an expected result.

As a stopgap solution, consider allowing components to check, early after the MNA solver generates a solution, whether or not something "surprising" (by their own definition--such as a current inversion) happened within the last tick, and, if so, they may change their parameters and simulate the _previous_ tick again--effectively rolling back simulation time. This may need to happen multiple times as a cascade of "surprising" results occurs throughout the network. Indeed, a significant risk of doing exactly this is having unstable solutions, where the iteration never converges. In such cases, the solver may simply have to give up after a fixed number of iterations.

The cost of doing a changed iteration should not be underestimated. In particular, many devices react by changing an intrinsic parameter, such as resistance, which requires rebuilding the MNA matrices and decomposing them, thus losing any efficiency gains caused by having those cached (and assuming that R changes infrequently). Up until now, that would happen at most once per game tick, which is apparently manageable for devices such as relays and switches. However, this proposal would suggest rebuilding a network _several_ times per game tick. While the number of active components that experience "surprising" results should be rather low, and thus a full set of iterations not needed in many cases, the _worst_ case behavior will likely be a slowdown proportional to the maximum number of iterations, and it is likely very possible (if discourageable) for a user to intentionally instigate exactly this behavior.

However, the proposed gain would definitely be a more realistic simulation, with things happening "all at once" as they would in a physical implementation (where the quantization would be too small to notice brief transients). This, in particular, would allow the aforementioned boost/buck inductor kickback circuit to work as it would "on paper", rather than having to rely on a workaround to achieve the same result. It would also drastically improve convergence time of large logic circuits implemented in signal networks by effectively eliding gate delay (up to a maximum).

Exact definitions of which components experience surprising conditions (and react to them in the next tick) would be needed to understand which components can benefit from this, and how to structure the program. Presently, this list likely includes:
- Diodes (react to current inversions by changing resistance)
- Generators/Motors (react to V changes by changing their internal V source)
- Relays (react to signal V by changing resistance)
- Gates, in the "cheap" solver (react to signal V by changing output signal V)--it should be possible to have a much higher max iteration parameter for this solver, since it's not nearly as involved, but beware that it is incredibly easy to make unstable logic circuits

Notable non-participants include:
- Switches (they react to player input, which is outside of the simulation)
- Capacitors/Inductors (react to dV/dt / dI/dt respectively, which should be handled within the simulation's "full steps" and not any of the approximation iterations)

More are welcome (add comments and I'll incorporate them).

The only way to reasonably test this hypothesis is to implement and profile; as of right now, this is not a high priority.

**Comment by OmegaHaxors** [comment]
Here's my contribution to this discussion https://media.discordapp.net/attachments/463476601116426243/469499372946718731/unknown.png?width=544&height=679

**Comment by jrddunbr** [comment]
I was looking at the code, and I think that the way that the Thevenin systems are done right now already actually do this - they call solve() twice per their FastProcess loops.

**Comment by Grissess** [comment]
They may do some iteration substeps, but it doesn't go far enough if it doesn't allow simulation of the previous tick's parameters (a must for catching the one-frame inductive kickback, for example). Yes, there is _some_ iteration happening there to get Thevenin decompositions, but none of it allows retrograde changes to, e.g., network connectivity.

**Comment by jrddunbr** [comment]
Rip me then. May be a good idea to do it at some point though, we may need to solve at least part of this to get InterSystem usable.

**Comment by jrddunbr** [comment]
I've been thinking about this for a long time, and it's similar to where I was going with the 1.16.x and kmna updates. It has become clear to me that while kmna was well intended, I don't think that it can be finished in good faith until we've really resolved some big problems with theoretical electrical circuits. My final goal would be to make everything isolated and use dozens of two port networks, which would allow for smaller segments to be run more often. I think that this would allow for some of the things you want to do and keep it all in real time.

**Comment by jrddunbr** [comment]
This issue is being closed now since there will be no more feature updates in Electrical Age for Minecraft 1.7.10.
If the issue is relevant to 1.12, it will be re-opened there at a later date.
