### ISSUE TITLE
Update Developers in README.md?

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#77]
I'm not usually the first to demand credit for any work, but we're a pretty active fork, and I'm not the only contributor. Shall we update the developers [around here](https://github.com/jrddunbr/ElectricalAge#main-developers) in the README?

To my knowledge, we have:

- @jrddunbr;
- @OmegaHaxors;
- @lashtear; and
- myself;

...but do let me know if I'm forgetting anyone!

**Comment by jrddunbr** [comment]
Also, see #64

**Comment by jrddunbr** [comment]
Resolved
