### ISSUE TITLE
Refactor Eln.java

### ISSUE THREAD

**Issue by Grissess** [jrddunbr/ElectricalAge#82]
Every time I look at the actual mod class, I get angry.

There are a lot of things we can't (and shouldn't) change in this file, such as the reservation for 6-bits worth of ID out of a 16-bit integer for most item/block "subclasses", but I'd be very much happier if the code didn't look like...well, what it looks like now.

In particular:
- Remove all the anonymous scopes and refactor them into function calls, if at all possible;
- Spend some time recategorizing some items, or renaming the functions that register them to reflect the items they contain better;
- Move registration and recipes for the same item _close to each other_, so there's a single source of truth for each item and block in the mod without having to search all over the place for instances;
- Make some of the use of vanilla items and oredict in recipes a bit more consistent;
- Fix some blatant inconsistencies in naming, especially temporary variables;
- Probably more I'm forgetting.

This should probably be held off until #68, because that also touches this file quite a lot.

**Comment by jrddunbr** [comment]
Yeahhhhhhhhh, I can do some work with this. It's going to be part of the MNA refactor.

**Comment by jrddunbr** [comment]
there's going to be a shitton of stuff done in that.

**Comment by jrddunbr** [comment]
I'm considering what it would take to re-id all of the parts of the mod, since it's just a disaster at this point. Not sure about world compatibility, but I may just make a shim mod that converts them all between the older versions and the new one I make, or something like that. It's a mess.

**Comment by jrddunbr** [comment]
I'm not going to re-id everything at this time, I don't think. I also think that while the anonymous `subId` and `name` variables in the anonymous inner contexts can be confusing at first, I can't see a viable alternative for things like building the descriptors up, it's sensible for the time being unless someone can think up an interface and move said code somewhere.

Fixed in #136
